version: '3.9'

services:
  db:
    image: postgres:14.4
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/01_create_table.sql
      - ./src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/02_add_data_table.sql
    networks:
      - postgres

  app:
    build: .
    depends_on:
      - db
    container_name: app
    restart: always
    networks:
      - postgres
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/cinema || kill 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 3s

networks:
  postgres:
    driver: bridge
